// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cerbos/cloud/apikey/v1/apikey.proto
// </auto-generated>
// Original file comments:
// Copyright 2021-2025 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cerbos.Api.Cloud.V1.ApiKey {
  public static partial class ApiKeyService
  {
    static readonly string __ServiceName = "cerbos.cloud.apikey.v1.ApiKeyService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest> __Marshaller_cerbos_cloud_apikey_v1_IssueAccessTokenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse> __Marshaller_cerbos_cloud_apikey_v1_IssueAccessTokenResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest> __Marshaller_cerbos_cloud_apikey_v1_RegisterDeviceRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse> __Marshaller_cerbos_cloud_apikey_v1_RegisterDeviceResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest> __Marshaller_cerbos_cloud_apikey_v1_RefreshDeviceTokenRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse> __Marshaller_cerbos_cloud_apikey_v1_RefreshDeviceTokenResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest, global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse> __Method_IssueAccessToken = new grpc::Method<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest, global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "IssueAccessToken",
        __Marshaller_cerbos_cloud_apikey_v1_IssueAccessTokenRequest,
        __Marshaller_cerbos_cloud_apikey_v1_IssueAccessTokenResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest, global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse> __Method_RegisterDevice = new grpc::Method<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest, global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "RegisterDevice",
        __Marshaller_cerbos_cloud_apikey_v1_RegisterDeviceRequest,
        __Marshaller_cerbos_cloud_apikey_v1_RegisterDeviceResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest, global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse> __Method_RefreshDeviceToken = new grpc::Method<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest, global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RefreshDeviceToken",
        __Marshaller_cerbos_cloud_apikey_v1_RefreshDeviceTokenRequest,
        __Marshaller_cerbos_cloud_apikey_v1_RefreshDeviceTokenResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cerbos.Api.Cloud.V1.ApiKey.ApikeyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of ApiKeyService</summary>
    [grpc::BindServiceMethod(typeof(ApiKeyService), "BindService")]
    public abstract partial class ApiKeyServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse> IssueAccessToken(global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task RegisterDevice(global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest request, grpc::IServerStreamWriter<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse> RefreshDeviceToken(global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for ApiKeyService</summary>
    public partial class ApiKeyServiceClient : grpc::ClientBase<ApiKeyServiceClient>
    {
      /// <summary>Creates a new client for ApiKeyService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ApiKeyServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for ApiKeyService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public ApiKeyServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ApiKeyServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected ApiKeyServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse IssueAccessToken(global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IssueAccessToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse IssueAccessToken(global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_IssueAccessToken, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse> IssueAccessTokenAsync(global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return IssueAccessTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse> IssueAccessTokenAsync(global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_IssueAccessToken, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse> RegisterDevice(global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RegisterDevice(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse> RegisterDevice(global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_RegisterDevice, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse RefreshDeviceToken(global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RefreshDeviceToken(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse RefreshDeviceToken(global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RefreshDeviceToken, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse> RefreshDeviceTokenAsync(global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RefreshDeviceTokenAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse> RefreshDeviceTokenAsync(global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RefreshDeviceToken, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override ApiKeyServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new ApiKeyServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(ApiKeyServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_IssueAccessToken, serviceImpl.IssueAccessToken)
          .AddMethod(__Method_RegisterDevice, serviceImpl.RegisterDevice)
          .AddMethod(__Method_RefreshDeviceToken, serviceImpl.RefreshDeviceToken).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, ApiKeyServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_IssueAccessToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenRequest, global::Cerbos.Api.Cloud.V1.ApiKey.IssueAccessTokenResponse>(serviceImpl.IssueAccessToken));
      serviceBinder.AddMethod(__Method_RegisterDevice, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceRequest, global::Cerbos.Api.Cloud.V1.ApiKey.RegisterDeviceResponse>(serviceImpl.RegisterDevice));
      serviceBinder.AddMethod(__Method_RefreshDeviceToken, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenRequest, global::Cerbos.Api.Cloud.V1.ApiKey.RefreshDeviceTokenResponse>(serviceImpl.RefreshDeviceToken));
    }

  }
}
#endregion
