// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cerbos/effect/v1/effect.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cerbos.Api.V1.Effect {

  /// <summary>Holder for reflection information generated from cerbos/effect/v1/effect.proto</summary>
  public static partial class EffectReflection {

    #region Descriptor
    /// <summary>File descriptor for cerbos/effect/v1/effect.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EffectReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch1jZXJib3MvZWZmZWN0L3YxL2VmZmVjdC5wcm90bxIQY2VyYm9zLmVmZmVj",
            "dC52MSpYCgZFZmZlY3QSFgoSRUZGRUNUX1VOU1BFQ0lGSUVEEAASEAoMRUZG",
            "RUNUX0FMTE9XEAESDwoLRUZGRUNUX0RFTlkQAhITCg9FRkZFQ1RfTk9fTUFU",
            "Q0gQA0JvChhkZXYuY2VyYm9zLmFwaS52MS5lZmZlY3RaPGdpdGh1Yi5jb20v",
            "Y2VyYm9zL2NlcmJvcy9hcGkvZ2VucGIvY2VyYm9zL2VmZmVjdC92MTtlZmZl",
            "Y3R2MaoCFENlcmJvcy5BcGkuVjEuRWZmZWN0YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Cerbos.Api.V1.Effect.Effect), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum Effect {
    [pbr::OriginalName("EFFECT_UNSPECIFIED")] Unspecified = 0,
    [pbr::OriginalName("EFFECT_ALLOW")] Allow = 1,
    [pbr::OriginalName("EFFECT_DENY")] Deny = 2,
    [pbr::OriginalName("EFFECT_NO_MATCH")] NoMatch = 3,
  }

  #endregion

}

#endregion Designer generated code
