---
auxData:
  jwt:
    keySets:
      - id: default
        local:
          file: /config/verify_key.jwk

engine:
  defaultPolicyVersion: "default"

schema:
  enforcement: reject

server:
  adminAPI:
    enabled: true
  grpcListenAddr: ":3593"
  httpListenAddr: ":3592"
  logRequestPayloads: true

storage:
  driver: "sqlite3"
  sqlite3:
    dsn: "file:///store/cerbos.sqlite?mode=rwc&cache=shared&_fk=true"

telemetry:
  disabled: true