---
server:
  httpListenAddr: ":3592"
  grpcListenAddr: ":3593"
  logRequestPayloads: true

auxData:
  jwt:
    keySets:
      - id: default
        local:
          file: /config/verify_key.jwk

engine:
  defaultPolicyVersion: "default"

schema:
  enforcement: reject

storage:
  driver: "disk"
  disk:
    directory: /policies
    watchForChanges: true

telemetry:
  disabled: true