// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cerbos/cloud/store/v1/store.proto
// </auto-generated>
// Original file comments:
// Copyright 2021-2025 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Cerbos.Api.Cloud.V1.Store {
  public static partial class CerbosStoreService
  {
    static readonly string __ServiceName = "cerbos.cloud.store.v1.CerbosStoreService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest> __Marshaller_cerbos_cloud_store_v1_ListFilesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse> __Marshaller_cerbos_cloud_store_v1_ListFilesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest> __Marshaller_cerbos_cloud_store_v1_GetCurrentVersionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse> __Marshaller_cerbos_cloud_store_v1_GetCurrentVersionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest> __Marshaller_cerbos_cloud_store_v1_GetFilesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse> __Marshaller_cerbos_cloud_store_v1_GetFilesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest> __Marshaller_cerbos_cloud_store_v1_ModifyFilesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse> __Marshaller_cerbos_cloud_store_v1_ModifyFilesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest> __Marshaller_cerbos_cloud_store_v1_ReplaceFilesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse> __Marshaller_cerbos_cloud_store_v1_ReplaceFilesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse> __Method_ListFiles = new grpc::Method<global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListFiles",
        __Marshaller_cerbos_cloud_store_v1_ListFilesRequest,
        __Marshaller_cerbos_cloud_store_v1_ListFilesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest, global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse> __Method_GetCurrentVersion = new grpc::Method<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest, global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCurrentVersion",
        __Marshaller_cerbos_cloud_store_v1_GetCurrentVersionRequest,
        __Marshaller_cerbos_cloud_store_v1_GetCurrentVersionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest, global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse> __Method_GetFiles = new grpc::Method<global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest, global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetFiles",
        __Marshaller_cerbos_cloud_store_v1_GetFilesRequest,
        __Marshaller_cerbos_cloud_store_v1_GetFilesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse> __Method_ModifyFiles = new grpc::Method<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ModifyFiles",
        __Marshaller_cerbos_cloud_store_v1_ModifyFilesRequest,
        __Marshaller_cerbos_cloud_store_v1_ModifyFilesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse> __Method_ReplaceFiles = new grpc::Method<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ReplaceFiles",
        __Marshaller_cerbos_cloud_store_v1_ReplaceFilesRequest,
        __Marshaller_cerbos_cloud_store_v1_ReplaceFilesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Cerbos.Api.Cloud.V1.Store.StoreReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of CerbosStoreService</summary>
    [grpc::BindServiceMethod(typeof(CerbosStoreService), "BindService")]
    public abstract partial class CerbosStoreServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse> ListFiles(global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse> GetCurrentVersion(global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse> GetFiles(global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse> ModifyFiles(global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse> ReplaceFiles(global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for CerbosStoreService</summary>
    public partial class CerbosStoreServiceClient : grpc::ClientBase<CerbosStoreServiceClient>
    {
      /// <summary>Creates a new client for CerbosStoreService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CerbosStoreServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for CerbosStoreService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public CerbosStoreServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CerbosStoreServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected CerbosStoreServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse ListFiles(global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListFiles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse ListFiles(global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse> ListFilesAsync(global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListFilesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse> ListFilesAsync(global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse GetCurrentVersion(global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCurrentVersion(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse GetCurrentVersion(global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCurrentVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse> GetCurrentVersionAsync(global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCurrentVersionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse> GetCurrentVersionAsync(global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCurrentVersion, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse GetFiles(global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFiles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse GetFiles(global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse> GetFilesAsync(global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetFilesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse> GetFilesAsync(global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse ModifyFiles(global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ModifyFiles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse ModifyFiles(global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ModifyFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse> ModifyFilesAsync(global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ModifyFilesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse> ModifyFilesAsync(global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ModifyFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse ReplaceFiles(global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReplaceFiles(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse ReplaceFiles(global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ReplaceFiles, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse> ReplaceFilesAsync(global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ReplaceFilesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse> ReplaceFilesAsync(global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ReplaceFiles, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override CerbosStoreServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CerbosStoreServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(CerbosStoreServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListFiles, serviceImpl.ListFiles)
          .AddMethod(__Method_GetCurrentVersion, serviceImpl.GetCurrentVersion)
          .AddMethod(__Method_GetFiles, serviceImpl.GetFiles)
          .AddMethod(__Method_ModifyFiles, serviceImpl.ModifyFiles)
          .AddMethod(__Method_ReplaceFiles, serviceImpl.ReplaceFiles).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CerbosStoreServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ListFiles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.Store.ListFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ListFilesResponse>(serviceImpl.ListFiles));
      serviceBinder.AddMethod(__Method_GetCurrentVersion, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionRequest, global::Cerbos.Api.Cloud.V1.Store.GetCurrentVersionResponse>(serviceImpl.GetCurrentVersion));
      serviceBinder.AddMethod(__Method_GetFiles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.Store.GetFilesRequest, global::Cerbos.Api.Cloud.V1.Store.GetFilesResponse>(serviceImpl.GetFiles));
      serviceBinder.AddMethod(__Method_ModifyFiles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.Store.ModifyFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ModifyFilesResponse>(serviceImpl.ModifyFiles));
      serviceBinder.AddMethod(__Method_ReplaceFiles, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesRequest, global::Cerbos.Api.Cloud.V1.Store.ReplaceFilesResponse>(serviceImpl.ReplaceFiles));
    }

  }
}
#endregion
