// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cerbos/svc/v1/svc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cerbos.Api.V1.Svc {

  /// <summary>Holder for reflection information generated from cerbos/svc/v1/svc.proto</summary>
  public static partial class SvcReflection {

    #region Descriptor
    /// <summary>File descriptor for cerbos/svc/v1/svc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SvcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdjZXJib3Mvc3ZjL3YxL3N2Yy5wcm90bxINY2VyYm9zLnN2Yy52MRofY2Vy",
            "Ym9zL3JlcXVlc3QvdjEvcmVxdWVzdC5wcm90bxohY2VyYm9zL3Jlc3BvbnNl",
            "L3YxL3Jlc3BvbnNlLnByb3RvGhxnb29nbGUvYXBpL2Fubm90YXRpb25zLnBy",
            "b3RvGhtnb29nbGUvYXBpL3Zpc2liaWxpdHkucHJvdG8aLnByb3RvYy1nZW4t",
            "b3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMucHJvdG8y1goKDUNlcmJv",
            "c1NlcnZpY2USpwIKEENoZWNrUmVzb3VyY2VTZXQSKi5jZXJib3MucmVxdWVz",
            "dC52MS5DaGVja1Jlc291cmNlU2V0UmVxdWVzdBosLmNlcmJvcy5yZXNwb25z",
            "ZS52MS5DaGVja1Jlc291cmNlU2V0UmVzcG9uc2UiuAGSQZ8BEgVDaGVjaxqT",
            "AVtEZXByZWNhdGVkOiBVc2UgQ2hlY2tSZXNvdXJjZXMgQVBJIGluc3RlYWRd",
            "IENoZWNrIHdoZXRoZXIgYSBwcmluY2lwYWwgaGFzIHBlcm1pc3Npb25zIHRv",
            "IHBlcmZvcm0gdGhlIGdpdmVuIGFjdGlvbnMgb24gYSBzZXQgb2YgcmVzb3Vy",
            "Y2UgaW5zdGFuY2VzLlgBgtPkkwIPOgEqIgovYXBpL2NoZWNrErYCChJDaGVj",
            "a1Jlc291cmNlQmF0Y2gSLC5jZXJib3MucmVxdWVzdC52MS5DaGVja1Jlc291",
            "cmNlQmF0Y2hSZXF1ZXN0Gi4uY2VyYm9zLnJlc3BvbnNlLnYxLkNoZWNrUmVz",
            "b3VyY2VCYXRjaFJlc3BvbnNlIsEBkkGZARIUQ2hlY2sgcmVzb3VyY2UgYmF0",
            "Y2gaf1tEZXByZWNhdGVkOiBVc2UgQ2hlY2tSZXNvdXJjZXMgQVBJIGluc3Rl",
            "YWRdIENoZWNrIGEgcHJpbmNpcGFsJ3MgcGVybWlzc2lvbnMgdG8gYSBiYXRj",
            "aCBvZiBoZXRlcm9nZW5lb3VzIHJlc291cmNlcyBhbmQgYWN0aW9ucy5YAYLT",
            "5JMCHjoBKiIZL2FwaS9jaGVja19yZXNvdXJjZV9iYXRjaBLwAQoOQ2hlY2tS",
            "ZXNvdXJjZXMSKC5jZXJib3MucmVxdWVzdC52MS5DaGVja1Jlc291cmNlc1Jl",
            "cXVlc3QaKi5jZXJib3MucmVzcG9uc2UudjEuQ2hlY2tSZXNvdXJjZXNSZXNw",
            "b25zZSKHAZJBZRIPQ2hlY2sgcmVzb3VyY2VzGlJDaGVjayBhIHByaW5jaXBh",
            "bCdzIHBlcm1pc3Npb25zIHRvIGEgYmF0Y2ggb2YgaGV0ZXJvZ2VuZW91cyBy",
            "ZXNvdXJjZXMgYW5kIGFjdGlvbnMugtPkkwIZOgEqIhQvYXBpL2NoZWNrL3Jl",
            "c291cmNlcxLFAQoKU2VydmVySW5mbxIkLmNlcmJvcy5yZXF1ZXN0LnYxLlNl",
            "cnZlckluZm9SZXF1ZXN0GiYuY2VyYm9zLnJlc3BvbnNlLnYxLlNlcnZlcklu",
            "Zm9SZXNwb25zZSJpkkFOEhZHZXQgc2VydmVyIGluZm9ybWF0aW9uGjRHZXQg",
            "aW5mb3JtYXRpb24gYWJvdXQgdGhlIHNlcnZlciBlLmcuIHNlcnZlciB2ZXJz",
            "aW9ugtPkkwISEhAvYXBpL3NlcnZlcl9pbmZvEoMCCg1QbGFuUmVzb3VyY2Vz",
            "EicuY2VyYm9zLnJlcXVlc3QudjEuUGxhblJlc291cmNlc1JlcXVlc3QaKS5j",
            "ZXJib3MucmVzcG9uc2UudjEuUGxhblJlc291cmNlc1Jlc3BvbnNlIp0BkkF8",
            "Eg5QbGFuIHJlc291cmNlcxpqUHJvZHVjZSBhIHF1ZXJ5IHBsYW4gd2l0aCBj",
            "b25kaXRpb25zIHRoYXQgbXVzdCBiZSBzYXRpc2ZpZWQgZm9yIGFjY2Vzc2lu",
            "ZyBhIHNldCBvZiBpbnN0YW5jZXMgb2YgYSByZXNvdXJjZYLT5JMCGDoBKiIT",
            "L2FwaS9wbGFuL3Jlc291cmNlcxohkkEeEhxDZXJib3MgUG9saWN5IERlY2lz",
            "aW9uIFBvaW50MsUPChJDZXJib3NBZG1pblNlcnZpY2USyQEKEUFkZE9yVXBk",
            "YXRlUG9saWN5EisuY2VyYm9zLnJlcXVlc3QudjEuQWRkT3JVcGRhdGVQb2xp",
            "Y3lSZXF1ZXN0Gi0uY2VyYm9zLnJlc3BvbnNlLnYxLkFkZE9yVXBkYXRlUG9s",
            "aWN5UmVzcG9uc2UiWJJBKRIWQWRkIG9yIHVwZGF0ZSBwb2xpY2llc2IPCg0K",
            "CUJhc2ljQXV0aBIAgtPkkwImOgEqWhI6ASoaDS9hZG1pbi9wb2xpY3kiDS9h",
            "ZG1pbi9wb2xpY3kSnAEKDExpc3RQb2xpY2llcxImLmNlcmJvcy5yZXF1ZXN0",
            "LnYxLkxpc3RQb2xpY2llc1JlcXVlc3QaKC5jZXJib3MucmVzcG9uc2UudjEu",
            "TGlzdFBvbGljaWVzUmVzcG9uc2UiOpJBIBINTGlzdCBwb2xpY2llc2IPCg0K",
            "CUJhc2ljQXV0aBIAgtPkkwIREg8vYWRtaW4vcG9saWNpZXMSjgEKCUdldFBv",
            "bGljeRIjLmNlcmJvcy5yZXF1ZXN0LnYxLkdldFBvbGljeVJlcXVlc3QaJS5j",
            "ZXJib3MucmVzcG9uc2UudjEuR2V0UG9saWN5UmVzcG9uc2UiNZJBHRIKR2V0",
            "IHBvbGljeWIPCg0KCUJhc2ljQXV0aBIAgtPkkwIPEg0vYWRtaW4vcG9saWN5",
            "EtMBCg1EaXNhYmxlUG9saWN5EicuY2VyYm9zLnJlcXVlc3QudjEuRGlzYWJs",
            "ZVBvbGljeVJlcXVlc3QaKS5jZXJib3MucmVzcG9uc2UudjEuRGlzYWJsZVBv",
            "bGljeVJlc3BvbnNlIm6SQSESDkRpc2FibGUgcG9saWN5Yg8KDQoJQmFzaWNB",
            "dXRoEgCC0+STAkRaGjoBKhoVL2FkbWluL3BvbGljeS9kaXNhYmxlWg8qDS9h",
            "ZG1pbi9wb2xpY3kiFS9hZG1pbi9wb2xpY3kvZGlzYWJsZRK8AQoMRW5hYmxl",
            "UG9saWN5EiYuY2VyYm9zLnJlcXVlc3QudjEuRW5hYmxlUG9saWN5UmVxdWVz",
            "dBooLmNlcmJvcy5yZXNwb25zZS52MS5FbmFibGVQb2xpY3lSZXNwb25zZSJa",
            "kkEgEg1FbmFibGUgcG9saWN5Yg8KDQoJQmFzaWNBdXRoEgCC0+STAjFaGToB",
            "KhoUL2FkbWluL3BvbGljeS9lbmFibGUiFC9hZG1pbi9wb2xpY3kvZW5hYmxl",
            "EsgBChNMaXN0QXVkaXRMb2dFbnRyaWVzEi0uY2VyYm9zLnJlcXVlc3QudjEu",
            "TGlzdEF1ZGl0TG9nRW50cmllc1JlcXVlc3QaLy5jZXJib3MucmVzcG9uc2Uu",
            "djEuTGlzdEF1ZGl0TG9nRW50cmllc1Jlc3BvbnNlIk+SQSkSFkxpc3QgYXVk",
            "aXQgbG9nIGVudHJpZXNiDwoNCglCYXNpY0F1dGgSAILT5JMCHRIbL2FkbWlu",
            "L2F1ZGl0bG9nL2xpc3Qve2tpbmR9MAESxwEKEUFkZE9yVXBkYXRlU2NoZW1h",
            "EisuY2VyYm9zLnJlcXVlc3QudjEuQWRkT3JVcGRhdGVTY2hlbWFSZXF1ZXN0",
            "Gi0uY2VyYm9zLnJlc3BvbnNlLnYxLkFkZE9yVXBkYXRlU2NoZW1hUmVzcG9u",
            "c2UiVpJBJxIUQWRkIG9yIHVwZGF0ZSBzY2hlbWFiDwoNCglCYXNpY0F1dGgS",
            "AILT5JMCJjoBKloSOgEqGg0vYWRtaW4vc2NoZW1hIg0vYWRtaW4vc2NoZW1h",
            "EpcBCgtMaXN0U2NoZW1hcxIlLmNlcmJvcy5yZXF1ZXN0LnYxLkxpc3RTY2hl",
            "bWFzUmVxdWVzdBonLmNlcmJvcy5yZXNwb25zZS52MS5MaXN0U2NoZW1hc1Jl",
            "c3BvbnNlIjiSQR8SDExpc3Qgc2NoZW1hc2IPCg0KCUJhc2ljQXV0aBIAgtPk",
            "kwIQEg4vYWRtaW4vc2NoZW1hcxKOAQoJR2V0U2NoZW1hEiMuY2VyYm9zLnJl",
            "cXVlc3QudjEuR2V0U2NoZW1hUmVxdWVzdBolLmNlcmJvcy5yZXNwb25zZS52",
            "MS5HZXRTY2hlbWFSZXNwb25zZSI1kkEdEgpHZXQgc2NoZW1hYg8KDQoJQmFz",
            "aWNBdXRoEgCC0+STAg8SDS9hZG1pbi9zY2hlbWESmgEKDERlbGV0ZVNjaGVt",
            "YRImLmNlcmJvcy5yZXF1ZXN0LnYxLkRlbGV0ZVNjaGVtYVJlcXVlc3QaKC5j",
            "ZXJib3MucmVzcG9uc2UudjEuRGVsZXRlU2NoZW1hUmVzcG9uc2UiOJJBIBIN",
            "RGVsZXRlIHNjaGVtYWIPCg0KCUJhc2ljQXV0aBIAgtPkkwIPKg0vYWRtaW4v",
            "c2NoZW1hEpwBCgtSZWxvYWRTdG9yZRIlLmNlcmJvcy5yZXF1ZXN0LnYxLlJl",
            "bG9hZFN0b3JlUmVxdWVzdBonLmNlcmJvcy5yZXNwb25zZS52MS5SZWxvYWRT",
            "dG9yZVJlc3BvbnNlIj2SQR8SDFJlbG9hZCBzdG9yZWIPCg0KCUJhc2ljQXV0",
            "aBIAgtPkkwIVEhMvYWRtaW4vc3RvcmUvcmVsb2FkGiKSQR8SHUNlcmJvcyBh",
            "ZG1pbmlzdHJhdGlvbiBzZXJ2aWNlMvcEChdDZXJib3NQbGF5Z3JvdW5kU2Vy",
            "dmljZRKXAQoSUGxheWdyb3VuZFZhbGlkYXRlEiwuY2VyYm9zLnJlcXVlc3Qu",
            "djEuUGxheWdyb3VuZFZhbGlkYXRlUmVxdWVzdBouLmNlcmJvcy5yZXNwb25z",
            "ZS52MS5QbGF5Z3JvdW5kVmFsaWRhdGVSZXNwb25zZSIjgtPkkwIdOgEqIhgv",
            "YXBpL3BsYXlncm91bmQvdmFsaWRhdGUShwEKDlBsYXlncm91bmRUZXN0Eigu",
            "Y2VyYm9zLnJlcXVlc3QudjEuUGxheWdyb3VuZFRlc3RSZXF1ZXN0GiouY2Vy",
            "Ym9zLnJlc3BvbnNlLnYxLlBsYXlncm91bmRUZXN0UmVzcG9uc2UiH4LT5JMC",
            "GToBKiIUL2FwaS9wbGF5Z3JvdW5kL3Rlc3QSlwEKElBsYXlncm91bmRFdmFs",
            "dWF0ZRIsLmNlcmJvcy5yZXF1ZXN0LnYxLlBsYXlncm91bmRFdmFsdWF0ZVJl",
            "cXVlc3QaLi5jZXJib3MucmVzcG9uc2UudjEuUGxheWdyb3VuZEV2YWx1YXRl",
            "UmVzcG9uc2UiI4LT5JMCHToBKiIYL2FwaS9wbGF5Z3JvdW5kL2V2YWx1YXRl",
            "EosBCg9QbGF5Z3JvdW5kUHJveHkSKS5jZXJib3MucmVxdWVzdC52MS5QbGF5",
            "Z3JvdW5kUHJveHlSZXF1ZXN0GisuY2VyYm9zLnJlc3BvbnNlLnYxLlBsYXln",
            "cm91bmRQcm94eVJlc3BvbnNlIiCC0+STAho6ASoiFS9hcGkvcGxheWdyb3Vu",
            "ZC9wcm94eRoQ+tLkkwIKEghJTlRFUk5BTELhAQoVZGV2LmNlcmJvcy5hcGku",
            "djEuc3ZjWjZnaXRodWIuY29tL2NlcmJvcy9jZXJib3MvYXBpL2dlbnBiL2Nl",
            "cmJvcy9zdmMvdjE7c3ZjdjGqAhFDZXJib3MuQXBpLlYxLlN2Y5JBexI/CgZD",
            "ZXJib3MiLQoGQ2VyYm9zEhJodHRwczovL2NlcmJvcy5kZXYaD2luZm9AY2Vy",
            "Ym9zLmRldjIGbGF0ZXN0KgECMhBhcHBsaWNhdGlvbi9qc29uOhBhcHBsaWNh",
            "dGlvbi9qc29uWhEKDwoJQmFzaWNBdXRoEgIIAWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cerbos.Api.V1.Request.RequestReflection.Descriptor, global::Cerbos.Api.V1.Response.ResponseReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.VisibilityReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
