// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cerbos/svc/v1/svc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cerbos.Api.V1.Svc {

  /// <summary>Holder for reflection information generated from cerbos/svc/v1/svc.proto</summary>
  public static partial class SvcReflection {

    #region Descriptor
    /// <summary>File descriptor for cerbos/svc/v1/svc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SvcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdjZXJib3Mvc3ZjL3YxL3N2Yy5wcm90bxINY2VyYm9zLnN2Yy52MRofY2Vy",
            "Ym9zL3JlcXVlc3QvdjEvcmVxdWVzdC5wcm90bxohY2VyYm9zL3Jlc3BvbnNl",
            "L3YxL3Jlc3BvbnNlLnByb3RvGhxnb29nbGUvYXBpL2Fubm90YXRpb25zLnBy",
            "b3RvGi5wcm90b2MtZ2VuLW9wZW5hcGl2Mi9vcHRpb25zL2Fubm90YXRpb25z",
            "LnByb3RvMvIKCg1DZXJib3NTZXJ2aWNlEqcCChBDaGVja1Jlc291cmNlU2V0",
            "EiouY2VyYm9zLnJlcXVlc3QudjEuQ2hlY2tSZXNvdXJjZVNldFJlcXVlc3Qa",
            "LC5jZXJib3MucmVzcG9uc2UudjEuQ2hlY2tSZXNvdXJjZVNldFJlc3BvbnNl",
            "IrgBkkGfARIFQ2hlY2sakwFbRGVwcmVjYXRlZDogVXNlIENoZWNrUmVzb3Vy",
            "Y2VzIEFQSSBpbnN0ZWFkXSBDaGVjayB3aGV0aGVyIGEgcHJpbmNpcGFsIGhh",
            "cyBwZXJtaXNzaW9ucyB0byBwZXJmb3JtIHRoZSBnaXZlbiBhY3Rpb25zIG9u",
            "IGEgc2V0IG9mIHJlc291cmNlIGluc3RhbmNlcy5YAYLT5JMCDzoBKiIKL2Fw",
            "aS9jaGVjaxK2AgoSQ2hlY2tSZXNvdXJjZUJhdGNoEiwuY2VyYm9zLnJlcXVl",
            "c3QudjEuQ2hlY2tSZXNvdXJjZUJhdGNoUmVxdWVzdBouLmNlcmJvcy5yZXNw",
            "b25zZS52MS5DaGVja1Jlc291cmNlQmF0Y2hSZXNwb25zZSLBAZJBmQESFENo",
            "ZWNrIHJlc291cmNlIGJhdGNoGn9bRGVwcmVjYXRlZDogVXNlIENoZWNrUmVz",
            "b3VyY2VzIEFQSSBpbnN0ZWFkXSBDaGVjayBhIHByaW5jaXBhbCdzIHBlcm1p",
            "c3Npb25zIHRvIGEgYmF0Y2ggb2YgaGV0ZXJvZ2VuZW91cyByZXNvdXJjZXMg",
            "YW5kIGFjdGlvbnMuWAGC0+STAh46ASoiGS9hcGkvY2hlY2tfcmVzb3VyY2Vf",
            "YmF0Y2gS8AEKDkNoZWNrUmVzb3VyY2VzEiguY2VyYm9zLnJlcXVlc3QudjEu",
            "Q2hlY2tSZXNvdXJjZXNSZXF1ZXN0GiouY2VyYm9zLnJlc3BvbnNlLnYxLkNo",
            "ZWNrUmVzb3VyY2VzUmVzcG9uc2UihwGSQWUSD0NoZWNrIHJlc291cmNlcxpS",
            "Q2hlY2sgYSBwcmluY2lwYWwncyBwZXJtaXNzaW9ucyB0byBhIGJhdGNoIG9m",
            "IGhldGVyb2dlbmVvdXMgcmVzb3VyY2VzIGFuZCBhY3Rpb25zLoLT5JMCGToB",
            "KiIUL2FwaS9jaGVjay9yZXNvdXJjZXMSxQEKClNlcnZlckluZm8SJC5jZXJi",
            "b3MucmVxdWVzdC52MS5TZXJ2ZXJJbmZvUmVxdWVzdBomLmNlcmJvcy5yZXNw",
            "b25zZS52MS5TZXJ2ZXJJbmZvUmVzcG9uc2UiaZJBThIWR2V0IHNlcnZlciBp",
            "bmZvcm1hdGlvbho0R2V0IGluZm9ybWF0aW9uIGFib3V0IHRoZSBzZXJ2ZXIg",
            "ZS5nLiBzZXJ2ZXIgdmVyc2lvboLT5JMCEhIQL2FwaS9zZXJ2ZXJfaW5mbxKf",
            "AgoNUGxhblJlc291cmNlcxInLmNlcmJvcy5yZXF1ZXN0LnYxLlBsYW5SZXNv",
            "dXJjZXNSZXF1ZXN0GikuY2VyYm9zLnJlc3BvbnNlLnYxLlBsYW5SZXNvdXJj",
            "ZXNSZXNwb25zZSK5AZJBfBIOUGxhbiByZXNvdXJjZXMaalByb2R1Y2UgYSBx",
            "dWVyeSBwbGFuIHdpdGggY29uZGl0aW9ucyB0aGF0IG11c3QgYmUgc2F0aXNm",
            "aWVkIGZvciBhY2Nlc3NpbmcgYSBzZXQgb2YgaW5zdGFuY2VzIG9mIGEgcmVz",
            "b3VyY2WC0+STAjQ6ASpaGjoBKiIVL2FwaS94L3BsYW4vcmVzb3VyY2VzIhMv",
            "YXBpL3BsYW4vcmVzb3VyY2VzGiGSQR4SHENlcmJvcyBQb2xpY3kgRGVjaXNp",
            "b24gUG9pbnQysAwKEkNlcmJvc0FkbWluU2VydmljZRLJAQoRQWRkT3JVcGRh",
            "dGVQb2xpY3kSKy5jZXJib3MucmVxdWVzdC52MS5BZGRPclVwZGF0ZVBvbGlj",
            "eVJlcXVlc3QaLS5jZXJib3MucmVzcG9uc2UudjEuQWRkT3JVcGRhdGVQb2xp",
            "Y3lSZXNwb25zZSJYkkEpEhZBZGQgb3IgdXBkYXRlIHBvbGljaWVzYg8KDQoJ",
            "QmFzaWNBdXRoEgCC0+STAiY6ASpaEjoBKhoNL2FkbWluL3BvbGljeSINL2Fk",
            "bWluL3BvbGljeRKcAQoMTGlzdFBvbGljaWVzEiYuY2VyYm9zLnJlcXVlc3Qu",
            "djEuTGlzdFBvbGljaWVzUmVxdWVzdBooLmNlcmJvcy5yZXNwb25zZS52MS5M",
            "aXN0UG9saWNpZXNSZXNwb25zZSI6kkEgEg1MaXN0IHBvbGljaWVzYg8KDQoJ",
            "QmFzaWNBdXRoEgCC0+STAhESDy9hZG1pbi9wb2xpY2llcxKOAQoJR2V0UG9s",
            "aWN5EiMuY2VyYm9zLnJlcXVlc3QudjEuR2V0UG9saWN5UmVxdWVzdBolLmNl",
            "cmJvcy5yZXNwb25zZS52MS5HZXRQb2xpY3lSZXNwb25zZSI1kkEdEgpHZXQg",
            "cG9saWN5Yg8KDQoJQmFzaWNBdXRoEgCC0+STAg8SDS9hZG1pbi9wb2xpY3kS",
            "yAEKE0xpc3RBdWRpdExvZ0VudHJpZXMSLS5jZXJib3MucmVxdWVzdC52MS5M",
            "aXN0QXVkaXRMb2dFbnRyaWVzUmVxdWVzdBovLmNlcmJvcy5yZXNwb25zZS52",
            "MS5MaXN0QXVkaXRMb2dFbnRyaWVzUmVzcG9uc2UiT5JBKRIWTGlzdCBhdWRp",
            "dCBsb2cgZW50cmllc2IPCg0KCUJhc2ljQXV0aBIAgtPkkwIdEhsvYWRtaW4v",
            "YXVkaXRsb2cvbGlzdC97a2luZH0wARLHAQoRQWRkT3JVcGRhdGVTY2hlbWES",
            "Ky5jZXJib3MucmVxdWVzdC52MS5BZGRPclVwZGF0ZVNjaGVtYVJlcXVlc3Qa",
            "LS5jZXJib3MucmVzcG9uc2UudjEuQWRkT3JVcGRhdGVTY2hlbWFSZXNwb25z",
            "ZSJWkkEnEhRBZGQgb3IgdXBkYXRlIHNjaGVtYWIPCg0KCUJhc2ljQXV0aBIA",
            "gtPkkwImOgEqWhI6ASoaDS9hZG1pbi9zY2hlbWEiDS9hZG1pbi9zY2hlbWES",
            "lwEKC0xpc3RTY2hlbWFzEiUuY2VyYm9zLnJlcXVlc3QudjEuTGlzdFNjaGVt",
            "YXNSZXF1ZXN0GicuY2VyYm9zLnJlc3BvbnNlLnYxLkxpc3RTY2hlbWFzUmVz",
            "cG9uc2UiOJJBHxIMTGlzdCBzY2hlbWFzYg8KDQoJQmFzaWNBdXRoEgCC0+ST",
            "AhASDi9hZG1pbi9zY2hlbWFzEo4BCglHZXRTY2hlbWESIy5jZXJib3MucmVx",
            "dWVzdC52MS5HZXRTY2hlbWFSZXF1ZXN0GiUuY2VyYm9zLnJlc3BvbnNlLnYx",
            "LkdldFNjaGVtYVJlc3BvbnNlIjWSQR0SCkdldCBzY2hlbWFiDwoNCglCYXNp",
            "Y0F1dGgSAILT5JMCDxINL2FkbWluL3NjaGVtYRKaAQoMRGVsZXRlU2NoZW1h",
            "EiYuY2VyYm9zLnJlcXVlc3QudjEuRGVsZXRlU2NoZW1hUmVxdWVzdBooLmNl",
            "cmJvcy5yZXNwb25zZS52MS5EZWxldGVTY2hlbWFSZXNwb25zZSI4kkEgEg1E",
            "ZWxldGUgc2NoZW1hYg8KDQoJQmFzaWNBdXRoEgCC0+STAg8qDS9hZG1pbi9z",
            "Y2hlbWESnAEKC1JlbG9hZFN0b3JlEiUuY2VyYm9zLnJlcXVlc3QudjEuUmVs",
            "b2FkU3RvcmVSZXF1ZXN0GicuY2VyYm9zLnJlc3BvbnNlLnYxLlJlbG9hZFN0",
            "b3JlUmVzcG9uc2UiPZJBHxIMUmVsb2FkIHN0b3JlYg8KDQoJQmFzaWNBdXRo",
            "EgCC0+STAhUSEy9hZG1pbi9zdG9yZS9yZWxvYWQaIpJBHxIdQ2VyYm9zIGFk",
            "bWluaXN0cmF0aW9uIHNlcnZpY2Uy5QQKF0NlcmJvc1BsYXlncm91bmRTZXJ2",
            "aWNlEpcBChJQbGF5Z3JvdW5kVmFsaWRhdGUSLC5jZXJib3MucmVxdWVzdC52",
            "MS5QbGF5Z3JvdW5kVmFsaWRhdGVSZXF1ZXN0Gi4uY2VyYm9zLnJlc3BvbnNl",
            "LnYxLlBsYXlncm91bmRWYWxpZGF0ZVJlc3BvbnNlIiOC0+STAh06ASoiGC9h",
            "cGkvcGxheWdyb3VuZC92YWxpZGF0ZRKHAQoOUGxheWdyb3VuZFRlc3QSKC5j",
            "ZXJib3MucmVxdWVzdC52MS5QbGF5Z3JvdW5kVGVzdFJlcXVlc3QaKi5jZXJi",
            "b3MucmVzcG9uc2UudjEuUGxheWdyb3VuZFRlc3RSZXNwb25zZSIfgtPkkwIZ",
            "OgEqIhQvYXBpL3BsYXlncm91bmQvdGVzdBKXAQoSUGxheWdyb3VuZEV2YWx1",
            "YXRlEiwuY2VyYm9zLnJlcXVlc3QudjEuUGxheWdyb3VuZEV2YWx1YXRlUmVx",
            "dWVzdBouLmNlcmJvcy5yZXNwb25zZS52MS5QbGF5Z3JvdW5kRXZhbHVhdGVS",
            "ZXNwb25zZSIjgtPkkwIdOgEqIhgvYXBpL3BsYXlncm91bmQvZXZhbHVhdGUS",
            "iwEKD1BsYXlncm91bmRQcm94eRIpLmNlcmJvcy5yZXF1ZXN0LnYxLlBsYXln",
            "cm91bmRQcm94eVJlcXVlc3QaKy5jZXJib3MucmVzcG9uc2UudjEuUGxheWdy",
            "b3VuZFByb3h5UmVzcG9uc2UiIILT5JMCGjoBKiIVL2FwaS9wbGF5Z3JvdW5k",
            "L3Byb3h5QuEBChVkZXYuY2VyYm9zLmFwaS52MS5zdmNaNmdpdGh1Yi5jb20v",
            "Y2VyYm9zL2NlcmJvcy9hcGkvZ2VucGIvY2VyYm9zL3N2Yy92MTtzdmN2MaoC",
            "EUNlcmJvcy5BcGkuVjEuU3ZjkkF7Ej8KBkNlcmJvcyItCgZDZXJib3MSEmh0",
            "dHBzOi8vY2VyYm9zLmRldhoPaW5mb0BjZXJib3MuZGV2MgZsYXRlc3QqAQIy",
            "EGFwcGxpY2F0aW9uL2pzb246EGFwcGxpY2F0aW9uL2pzb25aEQoPCglCYXNp",
            "Y0F1dGgSAggBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cerbos.Api.V1.Request.RequestReflection.Descriptor, global::Cerbos.Api.V1.Response.ResponseReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
