// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: cerbos/svc/v1/svc.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Cerbos.Api.V1.Svc {

  /// <summary>Holder for reflection information generated from cerbos/svc/v1/svc.proto</summary>
  public static partial class SvcReflection {

    #region Descriptor
    /// <summary>File descriptor for cerbos/svc/v1/svc.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SvcReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdjZXJib3Mvc3ZjL3YxL3N2Yy5wcm90bxINY2VyYm9zLnN2Yy52MRofY2Vy",
            "Ym9zL3JlcXVlc3QvdjEvcmVxdWVzdC5wcm90bxohY2VyYm9zL3Jlc3BvbnNl",
            "L3YxL3Jlc3BvbnNlLnByb3RvGhxnb29nbGUvYXBpL2Fubm90YXRpb25zLnBy",
            "b3RvGhtnb29nbGUvYXBpL3Zpc2liaWxpdHkucHJvdG8aLnByb3RvYy1nZW4t",
            "b3BlbmFwaXYyL29wdGlvbnMvYW5ub3RhdGlvbnMucHJvdG8y1goKDUNlcmJv",
            "c1NlcnZpY2USpwIKEENoZWNrUmVzb3VyY2VTZXQSKi5jZXJib3MucmVxdWVz",
            "dC52MS5DaGVja1Jlc291cmNlU2V0UmVxdWVzdBosLmNlcmJvcy5yZXNwb25z",
            "ZS52MS5DaGVja1Jlc291cmNlU2V0UmVzcG9uc2UiuAGSQZ8BEgVDaGVjaxqT",
            "AVtEZXByZWNhdGVkOiBVc2UgQ2hlY2tSZXNvdXJjZXMgQVBJIGluc3RlYWRd",
            "IENoZWNrIHdoZXRoZXIgYSBwcmluY2lwYWwgaGFzIHBlcm1pc3Npb25zIHRv",
            "IHBlcmZvcm0gdGhlIGdpdmVuIGFjdGlvbnMgb24gYSBzZXQgb2YgcmVzb3Vy",
            "Y2UgaW5zdGFuY2VzLlgBgtPkkwIPIgovYXBpL2NoZWNrOgEqErYCChJDaGVj",
            "a1Jlc291cmNlQmF0Y2gSLC5jZXJib3MucmVxdWVzdC52MS5DaGVja1Jlc291",
            "cmNlQmF0Y2hSZXF1ZXN0Gi4uY2VyYm9zLnJlc3BvbnNlLnYxLkNoZWNrUmVz",
            "b3VyY2VCYXRjaFJlc3BvbnNlIsEBkkGZARIUQ2hlY2sgcmVzb3VyY2UgYmF0",
            "Y2gaf1tEZXByZWNhdGVkOiBVc2UgQ2hlY2tSZXNvdXJjZXMgQVBJIGluc3Rl",
            "YWRdIENoZWNrIGEgcHJpbmNpcGFsJ3MgcGVybWlzc2lvbnMgdG8gYSBiYXRj",
            "aCBvZiBoZXRlcm9nZW5lb3VzIHJlc291cmNlcyBhbmQgYWN0aW9ucy5YAYLT",
            "5JMCHiIZL2FwaS9jaGVja19yZXNvdXJjZV9iYXRjaDoBKhLwAQoOQ2hlY2tS",
            "ZXNvdXJjZXMSKC5jZXJib3MucmVxdWVzdC52MS5DaGVja1Jlc291cmNlc1Jl",
            "cXVlc3QaKi5jZXJib3MucmVzcG9uc2UudjEuQ2hlY2tSZXNvdXJjZXNSZXNw",
            "b25zZSKHAZJBZRIPQ2hlY2sgcmVzb3VyY2VzGlJDaGVjayBhIHByaW5jaXBh",
            "bCdzIHBlcm1pc3Npb25zIHRvIGEgYmF0Y2ggb2YgaGV0ZXJvZ2VuZW91cyBy",
            "ZXNvdXJjZXMgYW5kIGFjdGlvbnMugtPkkwIZIhQvYXBpL2NoZWNrL3Jlc291",
            "cmNlczoBKhLFAQoKU2VydmVySW5mbxIkLmNlcmJvcy5yZXF1ZXN0LnYxLlNl",
            "cnZlckluZm9SZXF1ZXN0GiYuY2VyYm9zLnJlc3BvbnNlLnYxLlNlcnZlcklu",
            "Zm9SZXNwb25zZSJpkkFOEhZHZXQgc2VydmVyIGluZm9ybWF0aW9uGjRHZXQg",
            "aW5mb3JtYXRpb24gYWJvdXQgdGhlIHNlcnZlciBlLmcuIHNlcnZlciB2ZXJz",
            "aW9ugtPkkwISEhAvYXBpL3NlcnZlcl9pbmZvEoMCCg1QbGFuUmVzb3VyY2Vz",
            "EicuY2VyYm9zLnJlcXVlc3QudjEuUGxhblJlc291cmNlc1JlcXVlc3QaKS5j",
            "ZXJib3MucmVzcG9uc2UudjEuUGxhblJlc291cmNlc1Jlc3BvbnNlIp0BkkF8",
            "Eg5QbGFuIHJlc291cmNlcxpqUHJvZHVjZSBhIHF1ZXJ5IHBsYW4gd2l0aCBj",
            "b25kaXRpb25zIHRoYXQgbXVzdCBiZSBzYXRpc2ZpZWQgZm9yIGFjY2Vzc2lu",
            "ZyBhIHNldCBvZiBpbnN0YW5jZXMgb2YgYSByZXNvdXJjZYLT5JMCGCITL2Fw",
            "aS9wbGFuL3Jlc291cmNlczoBKhohkkEeEhxDZXJib3MgUG9saWN5IERlY2lz",
            "aW9uIFBvaW50MvgQChJDZXJib3NBZG1pblNlcnZpY2USyQEKEUFkZE9yVXBk",
            "YXRlUG9saWN5EisuY2VyYm9zLnJlcXVlc3QudjEuQWRkT3JVcGRhdGVQb2xp",
            "Y3lSZXF1ZXN0Gi0uY2VyYm9zLnJlc3BvbnNlLnYxLkFkZE9yVXBkYXRlUG9s",
            "aWN5UmVzcG9uc2UiWJJBKRIWQWRkIG9yIHVwZGF0ZSBwb2xpY2llc2IPCg0K",
            "CUJhc2ljQXV0aBIAgtPkkwImIg0vYWRtaW4vcG9saWN5OgEqWhIaDS9hZG1p",
            "bi9wb2xpY3k6ASoSsAEKD0luc3BlY3RQb2xpY2llcxIpLmNlcmJvcy5yZXF1",
            "ZXN0LnYxLkluc3BlY3RQb2xpY2llc1JlcXVlc3QaKy5jZXJib3MucmVzcG9u",
            "c2UudjEuSW5zcGVjdFBvbGljaWVzUmVzcG9uc2UiRZJBIxIQSW5zcGVjdCBw",
            "b2xpY2llc2IPCg0KCUJhc2ljQXV0aBIAgtPkkwIZEhcvYWRtaW4vcG9saWNp",
            "ZXMvaW5zcGVjdBKcAQoMTGlzdFBvbGljaWVzEiYuY2VyYm9zLnJlcXVlc3Qu",
            "djEuTGlzdFBvbGljaWVzUmVxdWVzdBooLmNlcmJvcy5yZXNwb25zZS52MS5M",
            "aXN0UG9saWNpZXNSZXNwb25zZSI6kkEgEg1MaXN0IHBvbGljaWVzYg8KDQoJ",
            "QmFzaWNBdXRoEgCC0+STAhESDy9hZG1pbi9wb2xpY2llcxKOAQoJR2V0UG9s",
            "aWN5EiMuY2VyYm9zLnJlcXVlc3QudjEuR2V0UG9saWN5UmVxdWVzdBolLmNl",
            "cmJvcy5yZXNwb25zZS52MS5HZXRQb2xpY3lSZXNwb25zZSI1kkEdEgpHZXQg",
            "cG9saWN5Yg8KDQoJQmFzaWNBdXRoEgCC0+STAg8SDS9hZG1pbi9wb2xpY3kS",
            "0wEKDURpc2FibGVQb2xpY3kSJy5jZXJib3MucmVxdWVzdC52MS5EaXNhYmxl",
            "UG9saWN5UmVxdWVzdBopLmNlcmJvcy5yZXNwb25zZS52MS5EaXNhYmxlUG9s",
            "aWN5UmVzcG9uc2UibpJBIRIORGlzYWJsZSBwb2xpY3liDwoNCglCYXNpY0F1",
            "dGgSAILT5JMCRCIVL2FkbWluL3BvbGljeS9kaXNhYmxlWhoaFS9hZG1pbi9w",
            "b2xpY3kvZGlzYWJsZToBKloPKg0vYWRtaW4vcG9saWN5ErwBCgxFbmFibGVQ",
            "b2xpY3kSJi5jZXJib3MucmVxdWVzdC52MS5FbmFibGVQb2xpY3lSZXF1ZXN0",
            "GiguY2VyYm9zLnJlc3BvbnNlLnYxLkVuYWJsZVBvbGljeVJlc3BvbnNlIlqS",
            "QSASDUVuYWJsZSBwb2xpY3liDwoNCglCYXNpY0F1dGgSAILT5JMCMSIUL2Fk",
            "bWluL3BvbGljeS9lbmFibGVaGRoUL2FkbWluL3BvbGljeS9lbmFibGU6ASoS",
            "yAEKE0xpc3RBdWRpdExvZ0VudHJpZXMSLS5jZXJib3MucmVxdWVzdC52MS5M",
            "aXN0QXVkaXRMb2dFbnRyaWVzUmVxdWVzdBovLmNlcmJvcy5yZXNwb25zZS52",
            "MS5MaXN0QXVkaXRMb2dFbnRyaWVzUmVzcG9uc2UiT5JBKRIWTGlzdCBhdWRp",
            "dCBsb2cgZW50cmllc2IPCg0KCUJhc2ljQXV0aBIAgtPkkwIdEhsvYWRtaW4v",
            "YXVkaXRsb2cvbGlzdC97a2luZH0wARLHAQoRQWRkT3JVcGRhdGVTY2hlbWES",
            "Ky5jZXJib3MucmVxdWVzdC52MS5BZGRPclVwZGF0ZVNjaGVtYVJlcXVlc3Qa",
            "LS5jZXJib3MucmVzcG9uc2UudjEuQWRkT3JVcGRhdGVTY2hlbWFSZXNwb25z",
            "ZSJWkkEnEhRBZGQgb3IgdXBkYXRlIHNjaGVtYWIPCg0KCUJhc2ljQXV0aBIA",
            "gtPkkwImIg0vYWRtaW4vc2NoZW1hOgEqWhIaDS9hZG1pbi9zY2hlbWE6ASoS",
            "lwEKC0xpc3RTY2hlbWFzEiUuY2VyYm9zLnJlcXVlc3QudjEuTGlzdFNjaGVt",
            "YXNSZXF1ZXN0GicuY2VyYm9zLnJlc3BvbnNlLnYxLkxpc3RTY2hlbWFzUmVz",
            "cG9uc2UiOJJBHxIMTGlzdCBzY2hlbWFzYg8KDQoJQmFzaWNBdXRoEgCC0+ST",
            "AhASDi9hZG1pbi9zY2hlbWFzEo4BCglHZXRTY2hlbWESIy5jZXJib3MucmVx",
            "dWVzdC52MS5HZXRTY2hlbWFSZXF1ZXN0GiUuY2VyYm9zLnJlc3BvbnNlLnYx",
            "LkdldFNjaGVtYVJlc3BvbnNlIjWSQR0SCkdldCBzY2hlbWFiDwoNCglCYXNp",
            "Y0F1dGgSAILT5JMCDxINL2FkbWluL3NjaGVtYRKaAQoMRGVsZXRlU2NoZW1h",
            "EiYuY2VyYm9zLnJlcXVlc3QudjEuRGVsZXRlU2NoZW1hUmVxdWVzdBooLmNl",
            "cmJvcy5yZXNwb25zZS52MS5EZWxldGVTY2hlbWFSZXNwb25zZSI4kkEgEg1E",
            "ZWxldGUgc2NoZW1hYg8KDQoJQmFzaWNBdXRoEgCC0+STAg8qDS9hZG1pbi9z",
            "Y2hlbWESnAEKC1JlbG9hZFN0b3JlEiUuY2VyYm9zLnJlcXVlc3QudjEuUmVs",
            "b2FkU3RvcmVSZXF1ZXN0GicuY2VyYm9zLnJlc3BvbnNlLnYxLlJlbG9hZFN0",
            "b3JlUmVzcG9uc2UiPZJBHxIMUmVsb2FkIHN0b3JlYg8KDQoJQmFzaWNBdXRo",
            "EgCC0+STAhUSEy9hZG1pbi9zdG9yZS9yZWxvYWQaIpJBHxIdQ2VyYm9zIGFk",
            "bWluaXN0cmF0aW9uIHNlcnZpY2Uy9wQKF0NlcmJvc1BsYXlncm91bmRTZXJ2",
            "aWNlEpcBChJQbGF5Z3JvdW5kVmFsaWRhdGUSLC5jZXJib3MucmVxdWVzdC52",
            "MS5QbGF5Z3JvdW5kVmFsaWRhdGVSZXF1ZXN0Gi4uY2VyYm9zLnJlc3BvbnNl",
            "LnYxLlBsYXlncm91bmRWYWxpZGF0ZVJlc3BvbnNlIiOC0+STAh0iGC9hcGkv",
            "cGxheWdyb3VuZC92YWxpZGF0ZToBKhKHAQoOUGxheWdyb3VuZFRlc3QSKC5j",
            "ZXJib3MucmVxdWVzdC52MS5QbGF5Z3JvdW5kVGVzdFJlcXVlc3QaKi5jZXJi",
            "b3MucmVzcG9uc2UudjEuUGxheWdyb3VuZFRlc3RSZXNwb25zZSIfgtPkkwIZ",
            "IhQvYXBpL3BsYXlncm91bmQvdGVzdDoBKhKXAQoSUGxheWdyb3VuZEV2YWx1",
            "YXRlEiwuY2VyYm9zLnJlcXVlc3QudjEuUGxheWdyb3VuZEV2YWx1YXRlUmVx",
            "dWVzdBouLmNlcmJvcy5yZXNwb25zZS52MS5QbGF5Z3JvdW5kRXZhbHVhdGVS",
            "ZXNwb25zZSIjgtPkkwIdIhgvYXBpL3BsYXlncm91bmQvZXZhbHVhdGU6ASoS",
            "iwEKD1BsYXlncm91bmRQcm94eRIpLmNlcmJvcy5yZXF1ZXN0LnYxLlBsYXln",
            "cm91bmRQcm94eVJlcXVlc3QaKy5jZXJib3MucmVzcG9uc2UudjEuUGxheWdy",
            "b3VuZFByb3h5UmVzcG9uc2UiIILT5JMCGiIVL2FwaS9wbGF5Z3JvdW5kL3By",
            "b3h5OgEqGhD60uSTAgoSCElOVEVSTkFMQuEBChVkZXYuY2VyYm9zLmFwaS52",
            "MS5zdmNaNmdpdGh1Yi5jb20vY2VyYm9zL2NlcmJvcy9hcGkvZ2VucGIvY2Vy",
            "Ym9zL3N2Yy92MTtzdmN2MaoCEUNlcmJvcy5BcGkuVjEuU3ZjkkF7Ej8KBkNl",
            "cmJvcyItCgZDZXJib3MSEmh0dHBzOi8vY2VyYm9zLmRldhoPaW5mb0BjZXJi",
            "b3MuZGV2MgZsYXRlc3QqAQIyEGFwcGxpY2F0aW9uL2pzb246EGFwcGxpY2F0",
            "aW9uL2pzb25aEQoPCglCYXNpY0F1dGgSAggBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Cerbos.Api.V1.Request.RequestReflection.Descriptor, global::Cerbos.Api.V1.Response.ResponseReflection.Descriptor, global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Api.VisibilityReflection.Descriptor, global::Grpc.Gateway.ProtocGenOpenapiv2.Options.AnnotationsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
