name: CI

on:
  pull_request:
    branches:
      - main
      - 'v*'

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  build-check-changes-and-run-unit-tests:
    name: Build, check uncommitted changes and run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          lfs: true
          persist-credentials: false

      - name: Set up Buf
        uses: cerbos/actions/install-tools@f822bd7b9c8db95f84086089f37ab0d23ca45400 # main
        with:
          tools: buf
  
      - name: Setup Cerbos
        uses: cerbos/cerbos-setup-action@f8061b1f07da2d185acd233dedaa5d5eadb99214 # v1.9.10
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          version: latest

      - name: Run the build script
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        with:
          cake-bootstrap: true
          target: Build

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@f822bd7b9c8db95f84086089f37ab0d23ca45400 # main

      - name: Run the test script
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        env:
          CERBOS_HUB_API_ENDPOINT: "${{ secrets.CERBOS_HUB_API_ENDPOINT }}"
          CERBOS_HUB_CLIENT_ID: "${{ secrets.CERBOS_HUB_CLIENT_ID }}"
          CERBOS_HUB_CLIENT_SECRET: "${{ secrets.CERBOS_HUB_CLIENT_SECRET }}"
          CERBOS_HUB_STORE_ID: "${{ secrets.CERBOS_HUB_STORE_ID }}"
        with:
          cake-bootstrap: true
          target: UnitTests
