---
name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Add mask for NUGET_API_KEY
        run: |
          echo "::add-mask::${{ secrets.NUGET_API_KEY }}" 

      - uses: actions/checkout@v4
          
      - uses: actions/setup-dotnet@v4
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        with:
          dotnet-version: |
            2.0.x
            2.1.x
            5.0.x
            6.0.x

      - name: Build the NuGeT package
        uses: cake-build/cake-action@v3
        with:
          cake-bootstrap: true
          target: Pack

      - name: Publish generated NuGeT package
        run: dotnet nuget push ./src/Sdk/bin/Release/Cerbos.Sdk.*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }} --skip-duplicate --no-symbols
