name: Release

on:
  push:
    tags:
      - '*'

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  release:
    name: Release NuGet package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: true
          persist-credentials: false

      - name: Set up .NET
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        env:
          DOTNET_NOLOGO: true
          DOTNET_CLI_TELEMETRY_OPTOUT: true
        with:
          dotnet-version: |
            2.0.x
            2.1.x
            8.0.x

      - name: Set up Buf
        uses: cerbos/actions/install-tools@0c9f5496bb1c168e663ad7ecb99ad0d2b947ba46 # main
        with:
          tools: buf

      - name: Run Clean
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        with:
          cake-bootstrap: true
          target: Clean

      - name: Run Generate
        uses: cake-build/cake-action@d218f1133bb74a1df0b08c89cfd8fc100c09e1a0 # v3.0.1
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        with:
          cake-bootstrap: true
          target: Generate

      - name: Build NuGet package
        run: dotnet pack -c Release /p:Version="${VERSION}" src/Sdk/sdk.csproj
        env:
          VERSION: ${{ github.ref_name }}

      - name: Check repo status
        uses: cerbos/actions/check-repo-status@0c9f5496bb1c168e663ad7ecb99ad0d2b947ba46 # main

      - name: Log in to NuGet
        id: nuget-login
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        with:
          user: ${{ secrets.NUGET_USER }}

      - name: Publish generated NuGet package
        run: dotnet nuget push src/Sdk/bin/Release/Cerbos.Sdk.*.nupkg -s https://api.NuGet.org/v3/index.json -k "${NUGET_API_KEY}" --skip-duplicate --no-symbols
        env:
          NUGET_API_KEY: ${{ steps.nuget-login.outputs.NUGET_API_KEY }}
